apiVersion: spec.keptn.sh/0.2.3
kind: Shipyard
metadata:
  name: kube-app
spec:
  stages:
    - name: development
      sequences:
        - name: delivery
          tasks:
            - name: deployment
            - name: test
              properties:
                teststrategy: functional
            - name: evaluation
              properties:
                timeframe: 5m
    - name: staging
      sequences:
        - name: delivery
          triggeredOn:
            - event: dev.delivery.finished
          tasks:
            - name: deployment
            - name: test
              properties:
                teststrategy: performance
            - name: evaluation
              properties:
                timeframe: 10m
        - name: rollback
          triggeredOn:
            - event: staging.evaluation.finished
              selector:
                match:
                  result: fail
          tasks:
            - name: rollback
    - name: production
      sequences:
        - name: delivery
          triggeredOn:
            - event: staging.delivery.finished
          tasks:
            - name: deployment
        - name: rollback
          triggeredOn:
            - event: production.evaluation.finished
              selector:
                match:
                  result: fail
          tasks:
            - name: rollback
